services:
  - type: web
    name: app
    branch: main
    runtime: static
    staticPublishPath: ./dist/
    buildCommand: pnpm i -g pnpm; pnpm install; cd apps/app; pnpm build
    buildFilter:
      paths:
        - apps/app/**
  - type: web
    name: docs
    branch: main
    runtime: static
    # rootDir: apps/docs
    staticPublishPath: ./dist/
    buildCommand: pnpm i -g pnpm; pnpm install;cd apps/docs; pnpm build
    buildFilter:
      paths:
        - apps/docs/**
