version: 2.1

orbs:
  bun: cmgriffing/bun-orb@0.0.22
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - bun/setup:
          version: 1.0.0
      - run: cd apps/git-auth && bun install && bun bake
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
