version: 2.1

orbs:
  bun-orb: cmgriffing/bun-orb@0.0.2

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - bun-orb/setup
      - run: >
          cd apps/git-auth
          bun bake
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
