version: "3.4"

services:
  php-custom:
    image: php-custom
    build: .
    ports:
      - 3456
    command: composer test
    # tty: true
    volumes:
      - $GITHUB_WORKSPACE/clients/php:/var/www/html
