version: "3.4"

services:
  php-custom:
    image: php-custom
    build: .
    command: composer test
    network_mode: host
    tty: true
    volumes:
      - ./:/var/www/html
      # - $GITHUB_WORKSPACE/clients/php:/var/www/html
