version: '3.4'

services:
  php-custom:
    image: php-custom
    build: .
    ports:
      - 3456
    command: tail -f /dev/null
    tty: true
    volumes:
      - /Volumes/T7/repos/vexilla/clients/php:/var/www/html

# volumes:
#   mount:
#     driver: local
#     driver_opts:
#       type: none
#       # device: ./log # this won't work
#       device: ":${PWD}/path"
#       o: bind
#       # type: nfs
#       # # o: addr=host.docker.internal,rw,nolock,hard,nfsvers=3