LanguageName = 'ocaml'
LanguageDisplayName = "OCaml"
InstallInstructions = '''
INSTALLATION
'''
CustomInstanceHash = "instanceId"
SyncFlags = "syncFlags"
SetupSnippet = '''
```ocaml
SETUP
```
'''
Should = "should"
UsageSnippet = '''
```ocaml
USAGE
```
'''
Example = '''
```ocaml
EXAMPLE
```
'''
API = '''

The full API documentation can be found at: [COMING SOON](https://ocaml.org/p/vexilla/latest/doc/index.html)

'''
