name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Bazel-supported languages
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - run: bazel build //...
      # - run: bazel test //...
      # PHP
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./clients/php/docker-compose.ci.yml"
          down-flags: "--volumes"
