name: Deploy
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - run: 'echo "TODO: This is where the deploy would happen."'
