name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      test-server:
        image: vexilla-test-server
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        # with:
        #   images: ghcr.io/vexilla-test-server

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/test-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Bazel-supported languages
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - run: bazel build //...
      # - run: bazel test //...
      # PHP
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./clients/php/docker-compose.ci.yml"
          down-flags: "--volumes"
